spring:
  application:
    name: system-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.234.193:3306/sourcestudy_system?serverTimezone=UTC&userUnicode=true&useSSL=false&
    username: root
    password: qazntiop4301nlf
# 日志文件配置路径
logging:
  config: classpath:log4j2-dev.xml


